<?php

namespace App\Repositories\Action;

use App\Repositories\ActionRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends ActionRepository
{
    /**
     * @inheritDoc
     */
    protected function getQueryBuilder(array $filter = [])
    {
        $builder = parent::getQueryBuilder($filter);

        if (isset($filter['entity']) &&
            null !== ($entity = $filter['entity'])) {
            $builder->andWhere("action.entity = :entity")
                    ->setParameter('entity', $entity);
        }

        return $builder;
    }
}
