<?php

namespace App\Repositories\Supplier;

use App\Entities;

/**
 * IncidenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidenceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Supplier $supplier
     * @return Incidence[]
     */
    function search(Entities\Supplier $supplier, int $status) 
    {
        return $this->createQueryBuilder('incidence')
                    ->andWhere('incidence.supplier = :supplier')
                    ->andWhere('incidence.status = :status')
                    ->setParameter('supplier', $supplier->getId())
                    ->setParameter('status', $status)
                    ->getQuery()
                    ->getResult();
    
    }
}
