<?php

namespace App\Repositories;

use App\Entities;

/**
 * AssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignmentRepository extends \Doctrine\ORM\EntityRepository
{
    use \LaravelDoctrine\ORM\Pagination\PaginatesFromRequest;

    /**
     *
     */
    function search(
        $perPage = 10, 
        $pageName= "page")
    {
        $builder = $this->createQueryBuilder('a');
        $builder->orderBy("a.created" , "desc");
        return $this->paginate($builder->getQuery(), $perPage, $pageName);
    }

    /**
     *
     */
    function years(
        $perPage = 10, 
        $pageName= "page")
    {
        $query = $this->getEntityManager()->createQuery("
            SELECT DISTINCT(DATE_FORMAT(a.created, '%y'))
            FROM App\Entities\Assignment a ORDER BY a.created DESC 
        ");
        return $this->paginate($query, $perPage, $pageName);
    }
}
