<?php

namespace App\Repositories;

use App\Entities\Department;

/**
 * AreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentRepository extends \Doctrine\ORM\EntityRepository
{
    use \LaravelDoctrine\ORM\Pagination\PaginatesFromRequest;

    /**
     * Get departments without children
     *
     * @param Department|null $exclude
     * @return Department[]
     */
    function childDepartments(Department $exclude = null) 
    {
        $sql = "
            SELECT d FROM \App\Entities\Department d
            LEFT JOIN d.children p
            WHERE p.id IS NULL
        ";

        if ($exclude) $sql .= "AND d.id != {$exclude->getId()}";

        return $this->getEntityManager()
                    ->createQuery($sql)
                    ->getResult();
    }
}
