<?php

namespace App\Repositories;

use App\Entities;

/**
 * InvoiceChargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceChargeRepository extends ChargeRepository
{
}
