<?php

namespace App\Repositories;

use App\Entities;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    use \LaravelDoctrine\ORM\Pagination\PaginatesFromRequest;

    /**
     *
     */
    function search(
        $sequence = null, 
        $from = null, 
        $to = null, 
        $department = null, 
        $area = null, 
        $supplier = null, 
        $type = null, 
        $status = null, 
        $sortBy = null, 
        $sort = null, 
        $perPage = 10, 
        $pageName= "page")
    {
        $builder = $this->createQueryBuilder('o')
                        ->innerJoin('o.area', 'a');

        if ($sequence !== null) {
            $builder->andWhere("o.sequence LIKE :sequence")
                    ->setParameter('sequence', "%{$sequence}%");
        }
        if ($from !== null) {
            $builder->andWhere("o.date >= :from")
                ->setParameter('from', $from);
        }
        if ($to !== null) {
            $builder->andWhere("o.date <= :to")
                ->setParameter('to', $to);
        }
        if ($area !== null) {
            $builder->andWhere("o.area = :area")
                ->setParameter('area', $area);
        }
        if ($supplier !== null) {
            $builder->andWhere("o.supplier = :supplier")
                    ->setParameter('supplier', $supplier);
        }
        if ($type !== null) {
            $builder->andWhere("a.type = :type")
                    ->setParameter('type', $type);
        }
        if ($department !== null) {
            $builder->innerJoin('a.department', 'd')
                    ->leftJoin('d.parents', 'p')
                    ->andWhere("a.department = :department")
                    ->orWhere("p.id = :department")
                    ->setParameter('department', $department);
        
        }
        if ($status !== null) {
            $builder->andWhere("o.status = :status")
                ->setParameter('status', $status);
        }

        $builder->orderBy("o.{$sortBy}" , $sort);

        //dd($builder->getQuery()->getSql(), $builder->getQuery()->getParameters());
        if ($perPage !== null) {
            return $this->paginate($builder->getQuery(), $perPage, $pageName);
        }

        return $builder->getQuery()->getResult();
    }
}
